apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: clean-and-download
        image: busybox
        command: ["sh","-c","cat https://raw.githubusercontent.com/sho1oms/DEVOPS/main/K8S/Lesson1/index.html > /www/ "]
      containers:
      - name: hosting
        image: nginx
        volumeMounts:
          - name: http-content
            mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: http-content
        hostPath: /tmp/www-content
        type: DirectoryOrCreate
