apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-myenv-setup
spec:
  containers:
  - name: ubuntu
    env:
    - name: SLEEP_TIME
      value: "10"
    - name: EXIT_CODE
      value: "2"
    image: ubuntu:18.04
    command: [ "/bin/sh","-c"]
    args: [ "sleep $(SLEEP_TIME) && exit $(EXIT_CODE)" ]
  restartPolicy: Never