apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:                                      # Declaration of container ports
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 3
      volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: nginx-conf
          subPath: index.html
          readOnly: true
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-index-html-configmap    
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy1
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp